import {
  BookOpenText,
  Brackets,
  ClipboardList,
  CodeXml,
  DatabaseZap,
  FileBadge,
  FileLock2,
  GitCompareArrows,
  IdCard,
  Inbox,
  KeyRound,
  Link2,
  LockKeyholeOpen,
  MailOpen,
  MapPinOff,
  Network,
  PenTool,
  Route,
  Sigma,
  VenetianMask,
  ArrowDownAZ,
  ArrowUpDown,
  BookmarkPlus,
  Database,
  Diff,
  FileStack,
  FileX,
  FolderPen,
  GitCompare,
  Grid3x3,
  ImagePlus,
  Layers2,
  PackagePlus,
  PaintBucket,
  Rows3,
  Squircle,
  TableProperties,
  TableRowsSplit,
  TextQuote,
  Activity,
  BookImage,
  ChartColumn,
  Combine,
  Contrast,
  Frame,
  PackageOpen,
  Proportions,
  RotateCcwSquare,
  ScanSearch,
  Shapes,
  Sheet,
  Sparkles,
  Table2,
  ArrowDownUp,
  BookOpen,
  Braces,
  FileCheck,
  FileDiff,
  FileOutput,
  FileSpreadsheet,
  Grid2x2,
  LockKeyhole,
  NotebookPen,
  Palette,
  Pilcrow,
  Table,
  AppWindow,
  ArchiveRestore,
  Binary,
  ArrowLeftRight,
  AudioLines,
  AudioWaveform,
  Blend,
  Captions,
  Clapperboard,
  CopyCheck,
  Crop,
  Eraser,
  FastForward,
  FileImage,
  FileMinus2,
  FileText,
  FileType,
  Film,
  Fingerprint,
  FolderArchive,
  Hash,
  Gauge,
  Headphones,
  Image,
  ImageDown,
  ImagePlay,
  Images,
  Languages,
  Layers,
  LayoutGrid,
  ListOrdered,
  Merge,
  MessageSquareText,
  Music,
  Music2,
  RefreshCw,
  Repeat,
  RotateCw,
  Scaling,
  ScanEye,
  Scissors,
  ShieldCheck,
  Shrink,
  Slice,
  Split,
  SquareSplitHorizontal,
  Stamp,
  Subtitles,
  Tag,
  Type,
  Volume2,
  VolumeX,
  FileCode,
  NotebookText,
  ListTree,
  TicketCheck,
  QrCode,
  ScanQrCode,
  TextSearch,
  ScrollText,
  Cpu,
  GitBranch,
  Rotate3d,
  Wrench,
  EyeOff,
  Columns2,
  BookMarked,
  ImageOff,
  ImageMinus,
  LayoutDashboard,
  Waypoints,
} from "lucide-react";

import type { ToolIconName } from "@/lib/tools";

/*
 * Resolves a registry icon key to a lucide icon.
 *
 * The indirection keeps lib/tools.ts free of React, so app/sitemap.ts can
 * import the registry without dragging icons into its module graph. A test
 * asserts every key in the union has an entry here.
 */
export const TOOL_ICONS = {
  audio: AudioLines,
  compress: Shrink,
  convert: RefreshCw,
  trim: Scissors,
  gif: ImagePlay,
  mute: VolumeX,
  clean: ShieldCheck,
  speed: Gauge,
  merge: Merge,
  subtitles: Captions,
  transcribe: MessageSquareText,
  music: Music,
  loudness: AudioWaveform,
  resize: Scaling,
  rotate: RotateCw,
  thumbnails: LayoutGrid,
  captions: FileText,
  burn: Type,
  channels: Headphones,
  waveform: Activity,
  chapters: ListOrdered,
  bilingual: Languages,
  split: Split,
  tracks: Layers,
  addaudio: Music2,
  volume: Volume2,
  sync: ArrowLeftRight,
  softsubs: Subtitles,
  loop: Repeat,
  film: Film,
  tags: Tag,
  cut: Slice,
  parts: SquareSplitHorizontal,
  clapper: Clapperboard,
  fade: Blend,
  tempo: FastForward,
  picture: Image,
  shrinkpicture: ImageDown,
  hidden: ScanEye,
  imagepdf: FileImage,
  deletepages: FileMinus2,
  numbers: Hash,
  checksum: Fingerprint,
  archive: FolderArchive,
  unarchive: ArchiveRestore,
  stamp: Stamp,
  frames: Images,
  crop: Crop,
  favicon: AppWindow,
  code: Binary,
  text: FileType,
  erase: Eraser,
  copies: CopyCheck,
  pages: FileOutput,
  reorder: ArrowDownUp,
  flatten: FileCheck,
  booklet: BookOpen,
  table: Table,
  spreadsheet: FileSpreadsheet,
  braces: Braces,
  notebook: NotebookPen,
  textfile: Pilcrow,
  lock: LockKeyhole,
  diff: FileDiff,
  collage: Grid2x2,
  palette: Palette,
  turn: RotateCcwSquare,
  frame: Frame,
  contrast: Contrast,
  shapes: Shapes,
  proportions: Proportions,
  pictures: BookImage,
  sheet: Sheet,
  grid: Table2,
  chart: ChartColumn,
  sparkles: Sparkles,
  scansearch: ScanSearch,
  combine: Combine,
  package: PackageOpen,
  squircle: Squircle,
  tiles: Grid3x3,
  compare: GitCompare,
  bucket: PaintBucket,
  blankpages: FileX,
  collate: Layers2,
  filestack: FileStack,
  imageplus: ImagePlus,
  difftext: Diff,
  bookmark: BookmarkPlus,
  rows: Rows3,
  rowsplit: TableRowsSplit,
  sortaz: ArrowDownAZ,
  tableprops: TableProperties,
  database: Database,
  textquote: TextQuote,
  updown: ArrowUpDown,
  folderpen: FolderPen,
  packageplus: PackagePlus,
  filelock: FileLock2,
  unlock: LockKeyholeOpen,
  clipboard: ClipboardList,
  book: BookOpenText,
  mailopen: MailOpen,
  inbox: Inbox,
  databasezap: DatabaseZap,
  link: Link2,
  comparearrows: GitCompareArrows,
  sigma: Sigma,
  mask: VenetianMask,
  codexml: CodeXml,
  brackets: Brackets,
  route: Route,
  mappinoff: MapPinOff,
  network: Network,
  filebadge: FileBadge,
  keyround: KeyRound,
  pentool: PenTool,
  idcard: IdCard,
  filecode: FileCode,
  notebooktext: NotebookText,
  listtree: ListTree,
  ticket: TicketCheck,
  qrcode: QrCode,
  scanqr: ScanQrCode,
  textsearch: TextSearch,
  scrolltext: ScrollText,
  binary: Binary,
  cpu: Cpu,
  gitbranch: GitBranch,
  type: Type,
  rotate3d: Rotate3d,
  wrench: Wrench,
  eyeoff: EyeOff,
  scaneye: ScanEye,
  columns: Columns2,
  bookmarked: BookMarked,
  imageoff: ImageOff,
  imageminus: ImageMinus,
  spritesheet: LayoutDashboard,
  waypoints: Waypoints,
} as const satisfies Record<ToolIconName, unknown>;

interface ToolIconProps {
  name: ToolIconName;
  className?: string;
}

export function ToolIcon({ name, className }: ToolIconProps) {
  const Icon = TOOL_ICONS[name];
  // Decorative: the tool name sits next to it, so a label here would be noise
  // for a screen reader rather than help.
  return <Icon aria-hidden="true" className={className} size={18} strokeWidth={1.75} />;
}
